run:
  modules-download-mode: readonly
  timeout: 15m
  tests: false
linters:
  disable-all: true
  enable:
    - errcheck
    - copyloopvar
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unparam
    - unused
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "^redefines-builtin-id:"
    - "^receiver-naming:"
    - "unexported-return:"
    - "context-as-argument:"
    - "and that stutters"
