run:
  modules-download-mode: readonly
linters:
  disable-all: true
  enable:
    - unused
    - exportloopref
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - revive # replaces golint
    - errcheck
    - typecheck
    - gofmt
    - gochecknoinits
    - unparam
    - gosec

issues:
  exclude:
    # Check this issue for more info: https://github.com/kyoh86/scopelint/issues/4
    - Using the variable on range scope `tc` in function literal
  max-issues-per-linter: 0
  # show all issues of one type instead of only 3
  max-same-issues: 0
