# Documentation for how to configure goreleaser can be found at https://goreleaser.com/customization/release/

version: 2
project_name: kyma

release:
  github:
    owner: kyma-project
    name: cli
  mode: replace
  # label as prerelease for prereleases and nightly builds
  prerelease: '{{ or ( contains .Tag "rc" ) ( contains .Tag "dev" ) }}'
  use_existing_draft: true
  replace_existing_artifacts: true
  replace_existing_draft: true
  name_template: '{{.Tag}}'
  # make latest on stable release
  make_latest: '{{ not ( or ( contains .Tag "rc" ) ( contains .Tag "dev" ) ) }}'

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./main.go
    ldflags:
      # use .Tag for release/prereleases and nightly-<SHA> for nightly builds
      - -X github.com/kyma-project/cli.v3/internal/cmd/version.version={{ if contains .Tag "dev" }}nightly-{{.ShortCommit}}{{else}}{{.Tag}}{{end}}
    goos:
      - darwin
      - linux
      - windows
    ignore:
      - goos: darwin
        goarch: "386"

archives:
  - id: foo
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"
changelog:
  # disable on nightly builds
  disable: '{{ contains .Tag "dev" }}'
