# Documentation for how to configure goreleaser can be found at https://goreleaser.com/customization/release/

version: 2
project_name: kyma

release:
  github:
    owner: kyma-project
    name: cli
  mode: replace
  prerelease: auto
  replace_existing_artifacts: true
  replace_existing_draft: true
  name_template: '{{.Tag}}'
  make_latest: '{{ not contains .Tag "rc" }}'

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./main.go
    goos:
      - darwin
      - linux
      - windows
    ignore:
      - goos: darwin
        goarch: "386"

archives:
  - id: foo
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"
