# Documentation for how to configure goreleaser can be found at http://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
project_name: kyma

release:
  github:
    owner: kyma-project
    name: cli
  mode: replace
  prerelease: "true"
  replace_existing_artifacts: true
  make_latest: false

  header: |
    This is a premature, unstable version built on each commit to the main branch. Use on your own risk.

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./main.go
    goos:
      - darwin
      - linux
      - windows
    ignore:
      - goos: darwin
        goarch: "386"

archives:
  - id: foo
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "v0.0.0-dev"
changelog:
  disable: true
