# Documentation for how to configure goreleaser can be found at http://goreleaser.com
project_name: kyma
release:
  github:
    owner: kyma-project
    name: cli
  prerelease: auto
before:
  hooks:
    - make resolve
builds:
- env:
  - CGO_ENABLED=0
  - IS_RELEASE=true
  - KYMA_VERSION=main
  ldflags: -s -w -X github.com/kyma-project/cli/cmd/kyma/version.Version={{.Version}} -X github.com/kyma-project/cli/cmd/kyma/alpha/deploy.defaultKymaVersion={{.Env.KYMA_VERSION}} -X github.com/kyma-project/cli/cmd/kyma/install.isRelease={{.Env.IS_RELEASE}} -X github.com/kyma-project/cli/cmd/kyma/alpha/deploy.isRelease={{.Env.IS_RELEASE}}
  main: ./cmd/
  goos:
    - darwin
    - linux
    - windows
  ignore:
    - goos: darwin
      goarch: 386
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
