module-name: cli
kind: kyma
mend:
  language: golang-mod
  exclude:
    - "**/test/**"
    - "**/*_test.go"
    - "**/mocks/**"
checkmarx-one:
  preset: go-default
  exclude:
    - "**/test/**"
    - "**/*_test.go"
    - "**/mocks/**"
