// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import (
	v1alpha1 "github.com/kyma-incubator/octopus/pkg/apis/testing/v1alpha1"
	mock "github.com/stretchr/testify/mock"
)

// LogsFetcher is an autogenerated mock type for the logsFetcher type
type LogsFetcher struct {
	mock.Mock
}

// Logs provides a mock function with given fields: result
func (_m *LogsFetcher) Logs(result v1alpha1.TestResult) (string, error) {
	ret := _m.Called(result)

	var r0 string
	if rf, ok := ret.Get(0).(func(v1alpha1.TestResult) string); ok {
		r0 = rf(result)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(v1alpha1.TestResult) error); ok {
		r1 = rf(result)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
