#!/usr/bin/env bash

# standard bash error handling
set -o nounset # treat unset variables as an error and exit immediately.
set -o errexit # exit immediately when a command fails.
set -E         # needs to be set if we want the ERR trap

readonly CLI_DIR="/home/prow/go/src/github.com/kyma-project/cli"

# locally delete the stable tag in order to have all the change logs listed under the new release version
delete_stable_tag() {
    if [[ $(git tag -l stable) ]]; then
        git tag -d stable
    fi
}

get_new_release_version() {
    # get the list of tags in a reverse chronological order
    TAG_LIST=($(git tag --sort=-creatordate))
    NEW_RELEASE_VERSION=${TAG_LIST[0]}
}

get_current_release_version() {
    # get the list of tags in a reverse chronological order excluding release candidate tags
    TAG_LIST_WITHOUT_RC=($(git tag --sort=-creatordate | grep -v -e "-rc"))
    if [[ $NEW_RELEASE_VERSION == *"-rc"* ]]; then
        CURRENT_RELEASE_VERSION=${TAG_LIST_WITHOUT_RC[0]}
    else
        CURRENT_RELEASE_VERSION=${TAG_LIST_WITHOUT_RC[1]}
    fi
}

main() {
    git remote add origin git@github.com:kyma-project/cli.git
    delete_stable_tag
    get_new_release_version
    get_current_release_version
    # release CLI with release notes generated by goreleaser
    curl -sL https://git.io/goreleaser | VERSION=v1.11.4 bash -s --
}

main
