#!/usr/bin/env bash

# standard bash error handling
set -o nounset # treat unset variables as an error and exit immediately.
set -o errexit # exit immediately when a command fails.

readonly CURRENT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

source "${CURRENT_DIR}/utilities.sh" || { echo 'Cannot load CI utilities.'; exit 1; }

generate_docs() {
    shout "Auto generate docs"
    make docs
}

check_generated_docs() {
    shout "Check that auto generated docs are up-to-date"
    # The first grep only includes all lines starting with + or -
    # The second grep excludes lines starting with --- a/ or +++ b/
    # The third grep excludes lines starting with +###### Auto generated by or -###### Auto generated by
    # If no lines were selected in one of the greps, then exit code will be 1 which is caught by [[ $? == 1 ]]
    result=$(git diff -U0 \
            | grep '^[+-]' \
            | grep -Ev '^(--- a/|\+\+\+ b/)' \
            | grep -v '^[+-]###### Auto generated by' || [[ $? == 1 ]])

    if [[ "${result}" != "" ]]; then
        echo "ERROR: detected documents that need to be updated" 
        echo "
        Run:
            make docs
        in the root of the repository and commit changes.
        "
        exit 1
    else
        echo -e "${GREEN}√ check that generated docs are up-to-date${NC}"
    fi
}

main() {
    generate_docs
    check_generated_docs
}

main