// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CmdRunner is an autogenerated mock type for the CmdRunner type
type CmdRunner struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, name, args
func (_m *CmdRunner) Run(ctx context.Context, name string, args ...string) (string, error) {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, ...string) string); ok {
		r0 = rf(ctx, name, args...)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = rf(ctx, name, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCmdRunner interface {
	mock.TestingT
	Cleanup(func())
}

// NewCmdRunner creates a new instance of CmdRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCmdRunner(t mockConstructorTestingTNewCmdRunner) *CmdRunner {
	mock := &CmdRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
