// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PathLooker is an autogenerated mock type for the PathLooker type
type PathLooker struct {
	mock.Mock
}

// Look provides a mock function with given fields: file
func (_m *PathLooker) Look(file string) (string, error) {
	ret := _m.Called(file)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(file)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPathLooker interface {
	mock.TestingT
	Cleanup(func())
}

// NewPathLooker creates a new instance of PathLooker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPathLooker(t mockConstructorTestingTNewPathLooker) *PathLooker {
	mock := &PathLooker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
