package run

import (
	"fmt"
	"math/rand"
	"strings"
	"time"

	oct "github.com/kyma-incubator/octopus/pkg/apis/testing/v1alpha1"
	"github.com/kyma-project/cli/internal/cli"
	"github.com/kyma-project/cli/internal/kube"
	"github.com/kyma-project/cli/pkg/api/octopus"
	"github.com/kyma-project/cli/cmd/kyma/test"
	"github.com/pkg/errors"
	"github.com/spf13/cobra"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

type command struct {
	opts *options
	cli.Command
}

func NewCmd(o *options) *cobra.Command {
	cmd := command{
		Command: cli.Command{Options: o.Options},
		opts:    o,
	}

	cobraCmd := &cobra.Command{
		Use:   "run <test-definition-1> <test-defintion-2> ... <test-definition-N>",
		Short: "Runs tests on a Kyma cluster.",
		Long: `Use this command to run tests on a Kyma cluster.

Remarks: 
If you don't provide any specific test definitions, all available test definitions will be added to the newly created test suite.
To execute all test defintions, run `+"`kyma test run -n example-test`"+`.

`,
		RunE:    func(_ *cobra.Command, args []string) error { return cmd.Run(args) },
		Aliases: []string{"r"},
	}

	cobraCmd.Flags().StringVarP(&o.Name, "name", "n", "", "Specifies the name of the new test suite. If you don't specify the value for the `-n` flag, the name of the test suite will be autogenerated.")
	cobraCmd.Flags().Int64VarP(&o.ExecutionCount, "count", "c", 1, "Defines how many times every test should be executed. ExecutionCount and MaxRetries flags are mutually exclusive.")
	cobraCmd.Flags().Int64VarP(&o.MaxRetries, "max-retries", "", 0, "Defines how many times a given test is retried when it fails. A suite is marked with a succeeded status even if some tests failed at first and then finally succeeded. The default value of 0 means that there are no retries of a given test.")
	cobraCmd.Flags().Int64VarP(&o.Concurrency, "concurrency", "", 1, "Specifies the number of tests to be executed in parallel.")
	cobraCmd.Flags().Bool("help", false, "Displays help for the command.")
	return cobraCmd
}

func (cmd *command) Run(args []string) error {
	var err error
	if cmd.K8s, err = kube.NewFromConfig("", cmd.KubeconfigPath); err != nil {
		return errors.Wrap(err, "Could not initialize the Kubernetes client. Make sure your kubeconfig is valid.")
	}

	var testSuiteName string
	if len(cmd.opts.Name) > 0 {
		testSuiteName = cmd.opts.Name
	} else {
		rand.Seed(time.Now().UTC().UnixNano())
		rnd := rand.Int31()
		testSuiteName = fmt.Sprintf("test-%d", rnd)
	}

	tNotExists, err := verifyIfTestNotExists(testSuiteName, cmd.K8s.Octopus())
	if err != nil {
		return err
	}
	if !tNotExists {
		return fmt.Errorf("Test suite '%s' already exists", testSuiteName)
	}

	clusterTestDefs, err := cmd.K8s.Octopus().ListTestDefinitions(metav1.ListOptions{})
	if err != nil {
		return errors.Wrap(err, "Unable to get the list of test definitions")
	}

	var testDefToApply []oct.TestDefinition
	if len(args) == 0 {
		testDefToApply = clusterTestDefs.Items
	} else {
		if testDefToApply, err = matchTestDefinitionNames(args,
			clusterTestDefs.Items); err != nil {
			return err
		}
	}

	testResource := generateTestsResource(testSuiteName,
		cmd.opts.ExecutionCount, cmd.opts.MaxRetries,
		cmd.opts.Concurrency, testDefToApply)
	if err != nil {
		return err
	}

	if _, err := cmd.K8s.Octopus().CreateTestSuite(testResource); err != nil {
		return err
	}

	fmt.Printf("test suite '%s' successfully created\r\n", testSuiteName)
	return nil
}

func matchTestDefinitionNames(testNames []string,
	testDefs []oct.TestDefinition) ([]oct.TestDefinition, error) {
	result := []oct.TestDefinition{}
	for _, tName := range testNames {
		found := false
		for _, tDef := range testDefs {
			if strings.ToLower(tName) == strings.ToLower(tDef.GetName()) {
				found = true
				result = append(result, tDef)
				break
			}
		}
		if !found {
			return nil, fmt.Errorf("Test defintion '%s' not found in the list of cluster test definitions", tName)
		}
	}
	return result, nil
}

func generateTestsResource(testName string, numberOfExecutions,
	maxRetries, concurrency int64,
	testDefinitions []oct.TestDefinition) *oct.ClusterTestSuite {

	octTestDefs := test.NewTestSuite(testName)
	matchNames := []oct.TestDefReference{}
	for _, td := range testDefinitions {
		matchNames = append(matchNames, oct.TestDefReference{
			Name:      td.GetName(),
			Namespace: td.GetNamespace(),
		})
	}
	octTestDefs.Spec.MaxRetries = maxRetries
	octTestDefs.Spec.Concurrency = concurrency
	octTestDefs.Spec.Count = numberOfExecutions
	octTestDefs.Spec.Selectors.MatchNames = matchNames

	return octTestDefs
}

func listTestSuiteNames(cli octopus.OctopusInterface) ([]string, error) {
	suites, err := cli.ListTestSuites(metav1.ListOptions{})
	if err != nil {
		return nil, errors.Wrap(err, "Unable to list test suites")
	}

	var result = make([]string, len(suites.Items))
	for i := 0; i < len(suites.Items); i++ {
		result[i] = suites.Items[i].GetName()
	}
	return result, nil
}

func verifyIfTestNotExists(suiteName string,
	cli octopus.OctopusInterface) (bool, error) {
	tests, err := listTestSuiteNames(cli)
	if err != nil {
		return false, err
	}
	for _, t := range tests {
		if t == suiteName {
			return false, nil
		}
	}
	return true, nil
}
