export default [
  { text: 'kyma', link: './gen-docs/kyma' },
  { text: 'kyma alpha', link: './gen-docs/kyma_alpha' },
  { text: 'kyma alpha authorize', link: './gen-docs/kyma_alpha_authorize' },
  { text: 'kyma alpha authorize group', link: './gen-docs/kyma_alpha_authorize_group' },
  { text: 'kyma alpha authorize repository', link: './gen-docs/kyma_alpha_authorize_repository' },
  { text: 'kyma alpha authorize serviceaccount', link: './gen-docs/kyma_alpha_authorize_serviceaccount' },
  { text: 'kyma alpha authorize user', link: './gen-docs/kyma_alpha_authorize_user' },
  { text: 'kyma alpha dashboard', link: './gen-docs/kyma_alpha_dashboard' },
  { text: 'kyma alpha dashboard start', link: './gen-docs/kyma_alpha_dashboard_start' },
  { text: 'kyma alpha dashboard stop', link: './gen-docs/kyma_alpha_dashboard_stop' },
  { text: 'kyma alpha diagnose', link: './gen-docs/kyma_alpha_diagnose' },
  { text: 'kyma alpha diagnose cluster', link: './gen-docs/kyma_alpha_diagnose_cluster' },
  { text: 'kyma alpha diagnose istio', link: './gen-docs/kyma_alpha_diagnose_istio' },
  { text: 'kyma alpha diagnose logs', link: './gen-docs/kyma_alpha_diagnose_logs' },
  { text: 'kyma alpha hana', link: './gen-docs/kyma_alpha_hana' },
  { text: 'kyma alpha hana map', link: './gen-docs/kyma_alpha_hana_map' },
  { text: 'kyma alpha kubeconfig', link: './gen-docs/kyma_alpha_kubeconfig' },
  { text: 'kyma alpha kubeconfig generate', link: './gen-docs/kyma_alpha_kubeconfig_generate' },
  { text: 'kyma alpha module', link: './gen-docs/kyma_alpha_module' },
  { text: 'kyma alpha module catalog', link: './gen-docs/kyma_alpha_module_catalog' },
  { text: 'kyma alpha provision', link: './gen-docs/kyma_alpha_provision' },
  { text: 'kyma alpha reference-instance', link: './gen-docs/kyma_alpha_reference-instance' },
  { text: 'kyma app', link: './gen-docs/kyma_app' },
  { text: 'kyma app push', link: './gen-docs/kyma_app_push' },
  { text: 'kyma completion', link: './gen-docs/kyma_completion' },
  { text: 'kyma completion bash', link: './gen-docs/kyma_completion_bash' },
  { text: 'kyma completion fish', link: './gen-docs/kyma_completion_fish' },
  { text: 'kyma completion powershell', link: './gen-docs/kyma_completion_powershell' },
  { text: 'kyma completion zsh', link: './gen-docs/kyma_completion_zsh' },
  { text: 'kyma help', link: './gen-docs/kyma_help' },
  { text: 'kyma module', link: './gen-docs/kyma_module' },
  { text: 'kyma module add', link: './gen-docs/kyma_module_add' },
  { text: 'kyma module catalog', link: './gen-docs/kyma_module_catalog' },
  { text: 'kyma module delete', link: './gen-docs/kyma_module_delete' },
  { text: 'kyma module list', link: './gen-docs/kyma_module_list' },
  { text: 'kyma module manage', link: './gen-docs/kyma_module_manage' },
  { text: 'kyma module pull', link: './gen-docs/kyma_module_pull' },
  { text: 'kyma module unmanage', link: './gen-docs/kyma_module_unmanage' },
  { text: 'kyma version', link: './gen-docs/kyma_version' },
];
