export default [
  { text: 'kyma', link: 'kyma' },
  { text: 'kyma alpha', link: 'kyma_alpha' },
  { text: 'kyma alpha diagnose', link: 'kyma_alpha_diagnose' },
  { text: 'kyma alpha hana', link: 'kyma_alpha_hana' },
  { text: 'kyma alpha hana map', link: 'kyma_alpha_hana_map' },
  { text: 'kyma alpha kubeconfig', link: 'kyma_alpha_kubeconfig' },
  { text: 'kyma alpha kubeconfig generate', link: 'kyma_alpha_kubeconfig_generate' },
  { text: 'kyma alpha provision', link: 'kyma_alpha_provision' },
  { text: 'kyma alpha reference-instance', link: 'kyma_alpha_reference-instance' },
  { text: 'kyma app', link: 'kyma_app' },
  { text: 'kyma app push', link: 'kyma_app_push' },
  { text: 'kyma completion', link: 'kyma_completion' },
  { text: 'kyma completion bash', link: 'kyma_completion_bash' },
  { text: 'kyma completion fish', link: 'kyma_completion_fish' },
  { text: 'kyma completion powershell', link: 'kyma_completion_powershell' },
  { text: 'kyma completion zsh', link: 'kyma_completion_zsh' },
  { text: 'kyma help', link: 'kyma_help' },
  { text: 'kyma module', link: 'kyma_module' },
  { text: 'kyma module add', link: 'kyma_module_add' },
  { text: 'kyma module catalog', link: 'kyma_module_catalog' },
  { text: 'kyma module delete', link: 'kyma_module_delete' },
  { text: 'kyma module list', link: 'kyma_module_list' },
  { text: 'kyma module manage', link: 'kyma_module_manage' },
  { text: 'kyma module pull', link: 'kyma_module_pull' },
  { text: 'kyma module unmanage', link: 'kyma_module_unmanage' },
  { text: 'kyma version', link: 'kyma_version' },
];
