apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  labels:
    app: test-kaniko
spec:
  # initContainers:
  #   - name: create-dockerfile
  #     image: alpine
  #     command:
  #     - 'sh'
  #     - '-c'
  #     - 'echo "FROM europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs18:main" > /workspace/Dockerfile'
  #     volumeMounts:
  #       - mountPath: /workspace
  #         name: workspace
  containers:
    - name: kaniko
      image: 'localhost:32137/pprecel/kaniko:ultra-tag'
      imagePullPolicy: Always
      args:
        - "--dockerfile=/workspace/Dockerfile"
        - "--context=dir:///workspace"
        - "--no-push"
      env: # this env points to empty file what cause no gce credential helper created by kaniko
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/dev/null"
      volumeMounts:
        - mountPath: /workspace
          name: workspace
  restartPolicy: Never
  serviceAccount: serverless-function 
  volumes:
    - name: workspace
      emptyDir: {}