apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspect
  namespace: kyma-system
spec:
  containers:
  - image: alpine
    imagePullPolicy: Always
    name: pvc-inspect
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "sleep 999999999999"
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/registry/
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: serverless-docker-registry