apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu
  name: ubuntu
spec:
  serviceAccount: serverless-function 
  containers:
  - image: localhost:32137/pprecel/kaniko:ultra-tag
    imagePullPolicy: Always
    name: ubuntu
