name: test-oidc

permissions:
  # Required to receive OIDC tokens
  # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#updating-your-actions-for-oidc
  id-token: write

on:
  push:

jobs:
  test-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Run test
        env:
          CA: "${{ secrets.CA }}"
          CLUSTER_SERVER: "${{ secrets.CLUSTER_SERVER }}"
        run: |
          go build -o test-oidc .
          ./test-oidc oidc --ca-certificate "${CA}" --cluster-server "${CLUSTER_SERVER}" --audience "gh-kubernetes-action" --output kubeconfig.yaml

          kubectl config view --kubeconfig=kubeconfig.yaml
          kubectl auth can-i --list --kubeconfig=kubeconfig.yaml
          kubectl get pods --kubeconfig=kubeconfig.yaml -A
