name: Pre-Release tag

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: push dev tag
        run: |
          git tag -f v0.0.0-dev
          git push -f origin v0.0.0-dev
