name: pull-cli-docs
on:
  pull_request:
    branches:
      - main
      - 'release-**'
  workflow_dispatch:
jobs:
  validate-docs:
    name: docs validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kyma CLI
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Run Docs Validation
        run: make validate
