name: TestSuite E2E. Scaffold Creation

on:
  push:
    branches:
      - main
      - 'release-**'
  pull_request:
    branches:
      - main
      - 'release-**'
    paths:
      - 'go.mod'
      - 'go.sum'
      - '**.go'
jobs:
  e2e:
    name: "Run E2E tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kyma CLI
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Build Kyma CLI
        run: |
          make resolve validate build-linux
          chmod +x ./bin/kyma-linux
          ls -la ./bin
          mv ./bin/kyma-linux /usr/local/bin/kyma
        timeout-minutes: 10
      - name: Run create scaffold test
        run: |
          make -C tests/e2e test-create-scaffold
        timeout-minutes: 3
